In [44]:
import numpy as np
import pandas as pd

In [3]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [5]:
arr = arr.reshape((2,16))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [8]:
arr=arr.reshape((4,8))
print(arr)
print(arr.T)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  8 16 24]
 [ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]]


In [11]:
stock_price_list = [10000,10300,9900,10500,11000]
stock_price_Series = pd.Series([10000,10300,9900,10500,11000])
stock_price_Series

0    10000
1    10300
2     9900
3    10500
4    11000
dtype: int64

In [14]:
print(stock_price_list[1:5])
print(stock_price_Series[1:5])

[10300, 9900, 10500, 11000]
1    10300
2     9900
3    10500
4    11000
dtype: int64


In [15]:
stock_price_Series_withIndex = pd.Series([10000,10300,9900,10500,11000],
                                         index=["2016-03-01","2016-03-02","2016-03-03","2016-03-04","2016-03-05"])
stock_price_Series_withIndex

2016-03-01    10000
2016-03-02    10300
2016-03-03     9900
2016-03-04    10500
2016-03-05    11000
dtype: int64

In [22]:
stock_price_Series_withIndex

for i,j in enumerate(stock_price_Series_withIndex) :
    print("Index : ", i ) # 정수인덱스값으로 돌림
    print("Value : ", j)
    
for i in range(len(stock_price_Series_withIndex)) :
    print("Index : ", stock_price_Series_withIndex.index[i] )
    print("Value : ", stock_price_Series_withIndex.values[i])
    
for i in stock_price_Series_withIndex.index :
    print(i)
    print(stock_price_Series_withIndex[i])

Index :  0
Value :  10000
Index :  1
Value :  10300
Index :  2
Value :  9900
Index :  3
Value :  10500
Index :  4
Value :  11000
Index :  2016-03-01
Value :  10000
Index :  2016-03-02
Value :  10300
Index :  2016-03-03
Value :  9900
Index :  2016-03-04
Value :  10500
Index :  2016-03-05
Value :  11000
2016-03-01
10000
2016-03-02
10300
2016-03-03
9900
2016-03-04
10500
2016-03-05
11000


In [23]:
stock_price_Series_withIndex[[1,2]] 
# list에서는 이런식으로 집어넣을수 없다
# 일반 list에서는 parameter가 보통 1개뿐이므로 index와 slice 값만 들어간다

2016-03-02    10300
2016-03-03     9900
dtype: int64

In [27]:
search_index = [0,3]

[stock_price_list[i] for i in search_index]

[10000, 10500]

In [28]:
stock_price_Series_withIndex+100

np.add(stock_price_Series_withIndex,100)

2016-03-01    20000
2016-03-02    20600
2016-03-03    19800
2016-03-04    21000
2016-03-05    22000
dtype: int64

In [29]:
stock_price_Series_withIndex[stock_price_Series_withIndex>10000]

2016-03-02    10300
2016-03-04    10500
2016-03-05    11000
dtype: int64

In [ ]:
stock_price_Series_withIndex[""]

In [30]:
11000 in stock_price_Series_withIndex
# in은 인덱스기준으로 잡힘(일반 벡터기준은 있는지 여부만 파악하는데)

False

In [31]:
11000 in stock_price_Series_withIndex.values

True

In [ ]:
# pandas index-value를 기준으로 흡수하는것

In [34]:
sdata = {"APPLE":1000, "MS":2000, "AMAZON":3000}
obj3 = pd.Series(sdata)

states = ["GOGGLE","APPLE","AMAZON"]
obj4 = pd.Series(sdata,states)


In [35]:
print(obj3+obj4)
print(obj3-obj4)

AMAZON    6000.0
APPLE     2000.0
GOGGLE       NaN
MS           NaN
dtype: float64
AMAZON    0.0
APPLE     0.0
GOGGLE    NaN
MS        NaN
dtype: float64


In [ ]:
# isnull : null값이니? 
# 값을 지우는 방법, 채우는 방법
# dropna(null값 지워), fillna(na값 채우기)

In [36]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [ ]:
# pandas Series : value 찾기 : at / iat
# index를 자기고 search : loc / iloc
# 만능? : ix

In [38]:
stock_price_Series_withIndex.at["2016-03-01"] # 단 한개
stock_price_Series_withIndex.iat[0]

10000

In [39]:
stock_price_Series_withIndex.iloc[[0,1]] #여러개

2016-03-01    10000
2016-03-02    10300
dtype: int64

In [40]:
stock_price_Series_withIndex.loc["2016-03-01":"2016-03-03"]

2016-03-01    10000
2016-03-02    10300
2016-03-03     9900
dtype: int64

In [41]:
stock_price_Series_withIndex[["2016-03-01","2016-03-03"]]

2016-03-01    10000
2016-03-03     9900
dtype: int64

In [ ]:
print(stock_price_Series_withIndex.count()) # len이나 count가 같음

In [43]:
# 기본적으로 index값이 unique 옵션이 걸려있지 않음
# 옵션에서 유니크 옵션을 줄수 있다 
add_data = pd.Series([12345],index=["2016-03-05"])
print(stock_price_Series_withIndex.append(add_data, verify_integrity = True))
print(stock_price_Series_withIndex)

ValueError: Indexes have overlapping values: Index(['2016-03-05'], dtype='object')

In [45]:
d = [0,1,2,3,4]
df = pd.DataFrame(d)
print(df)
print("-----")
ds = pd.Series(d)
print(ds)

   0
0  0
1  1
2  2
3  3
4  4
-----
0    0
1    1
2    2
3    3
4    4
dtype: int64


In [46]:
df.columns = ["column1"]
print(df)

   column1
0        0
1        1
2        2
3        3
4        4


In [49]:
df["newCol"] = d
print(df)
df["newCol2"] = 5
print(df)

   column1  newCol
0        0       0
1        1       1
2        2       2
3        3       3
4        4       4
   column1  newCol  newCol2
0        0       0        5
1        1       1        5
2        2       2        5
3        3       3        5
4        4       4        5


In [51]:
# 옆에 컬럼의 100배하기
df["newCol3"] = df["newCol2"]*100
print(df)

df["newCol2"][1] = 2000
# df.iloc[1,2] = 2000
print(df)


   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1        5      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500
   column1  newCol  newCol2  newCol3
0        0       0        5      500
1        1       1     2000      500
2        2       2        5      500
3        3       3        5      500
4        4       4        5      500


In [52]:
print(df.iloc[1,2]) # df[1,2] 이런식으로 에러남

del df["column1"]
print(df)

2000
   newCol  newCol2  newCol3
0       0        5      500
1       1     2000      500
2       2        5      500
3       3        5      500
4       4        5      500


In [53]:
df.index.name = "Count"
df

newCol  newCol2  newCol3
Count                          
0           0        5      500
1           1     2000      500
2           2        5      500
3           3        5      500
4           4        5      500

In [60]:
df.drop("newCol",1)
df

newCol  newCol2  newCol3
Count                          
0           0        5      500
1           1     2000      500
2           2        5      500
3           3        5      500
4           4        5      500

In [62]:
stock_price_DF_withIndex = pd.DataFrame([10000,10300,9900,10500,11000],
                                         index=["2016-03-01","2016-03-02","2016-03-03","2016-03-04","2016-03-05"])
stock_price_DF_withIndex

0
2016-03-01  10000
2016-03-02  10300
2016-03-03   9900
2016-03-04  10500
2016-03-05  11000

In [64]:
stock_price_DF_withIndex.rename(columns={0:"시가"},inplace = True)
# 컬럼 명이 인덱스에는 기본 정수형이기 때문에 "0":"시가" => 0:"시가" 
# 이런식으로 날려야함
stock_price_DF_withIndex

시가
2016-03-01  10000
2016-03-02  10300
2016-03-03   9900
2016-03-04  10500
2016-03-05  11000

In [69]:
stock_price_DF_withIndex["종가"] = [11000,12000,10000,13000,12000]
stock_price_DF_withIndex["고가"] = [13000,15000,15000,18000,17000]
stock_price_DF_withIndex["저가"] = [3000,5000,5000,8000,7000]
stock_price_DF_withIndex

시가     종가     고가    저가
2016-03-01  10000  11000  13000  3000
2016-03-02  10300  12000  15000  5000
2016-03-03   9900  10000  15000  5000
2016-03-04  10500  13000  18000  8000
2016-03-05  11000  12000  17000  7000

In [73]:
stock_price_DF_withIndex.iat[0,0]

시가    10000
종가    11000
고가    13000
저가     3000
Name: 2016-03-01, dtype: int64

In [78]:
stock_price_DF_withIndex.loc[:,"시가"]

2016-03-01    10000
2016-03-02    10300
2016-03-03     9900
2016-03-04    10500
2016-03-05    11000
Name: 시가, dtype: int64

In [84]:
stock_price_DF_withIndex.iloc[0,0:2]

stock_price_DF_withIndex.loc["2016-03-01",["시가","종가"]]

시가    10000
종가    11000
Name: 2016-03-01, dtype: int64

In [85]:
stock_price_DF_withIndex.loc["2016-03-01":"2016-03-03",:]

시가     종가     고가    저가
2016-03-01  10000  11000  13000  3000
2016-03-02  10300  12000  15000  5000
2016-03-03   9900  10000  15000  5000

In [86]:
stock_price_DF_withIndex.T # .T 축 바꾸기

2016-03-01  2016-03-02  2016-03-03  2016-03-04  2016-03-05
시가       10000       10300        9900       10500       11000
종가       11000       12000       10000       13000       12000
고가       13000       15000       15000       18000       17000
저가        3000        5000        5000        8000        7000

In [90]:
obj = pd.Series([-5.3,7.2,4.5,4.0],index=["c","b","a","f"])


obj #보간법(빈값에 대해서 채워서 처리하는 방법)

print(obj.reindex(["a","b","c","d","e","f"]).interpolate())

a    4.5
b    7.2
c   -5.3
d   -2.2
e    0.9
f    4.0
dtype: float64


In [100]:
df = pd.DataFrame([-5.3,4.5,7.2], index=["a","c","b"])

df.rename(columns = {0:"interPo"},inplace = True)

df = df.reindex(["a","d","e","c","b"])

df["newInterPo"] = df.iloc[:,0].interpolate()

df

interPo  newInterPo
a     -5.3   -5.300000
d      NaN   -2.033333
e      NaN    1.233333
c      4.5    4.500000
b      7.2    7.200000

In [101]:
p ={}

for i in range(5) :
    p[i+1] = 0
    
p[1]

{1: 0, 2: 0, 3: 0, 4: 0, 5: 0}

In [110]:
now = list(range(1,len(p)+1))
now

[1, 2, 3, 4, 5]

In [141]:
def minimumBribes(q):
    p = {}
    
    # initial count(check over2+)
    for i in range(len(q)) :
        p[i+1] = 0

    now = list(range(1,len(q)+1))
    print(now)
    count = 0
    for i in range(len(q)-1,-1,-1) :
        if(now[i] != q[i]) :
            p[now[i]] += 1
            if(p[now[i]] > 2) :
                return("Too chaotic")
                break
            tmp = now[i]
            now[i] = now[i-1]
            now[i-1] = tmp
            count += 1

            print(p)
            print(now)

    return(count)

q = [1, 2, 5, 3, 4, 7, 8, 6]
print(minimumBribes(q))

[1, 2, 3, 4, 5, 6, 7, 8]
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 1}
[1, 2, 3, 4, 5, 6, 8, 7]
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1, 7: 0, 8: 1}
[1, 2, 3, 4, 6, 5, 8, 7]
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 2, 7: 0, 8: 1}
[1, 2, 3, 6, 4, 5, 8, 7]
Too chaotic


In [137]:
p

{1: 0, 2: 0, 3: 0, 4: 0, 5: 0}

In [212]:
arr = [9, 2, 5, 3, 4, 7, 8, 6]

In [205]:
arr = [1, 2, 5, 3, 4, 7, 8, 6]
count = 0
for i in range(len(arr)) :
    if(min(arr[i:len(arr)]) != arr[i]) :
        tmp = arr[arr[i:len(arr)].index(min(arr[i:len(arr)]))+i]
        arr[arr[i:len(arr)].index(min(arr[i:len(arr)]))+i] = arr[i]
        arr[i] = tmp
        count+= 1
    print(arr)
print(count)

[1, 2, 5, 3, 4, 7, 8, 6]
[1, 2, 5, 3, 4, 7, 8, 6]
[1, 2, 3, 5, 4, 7, 8, 6]
[1, 2, 3, 4, 5, 7, 8, 6]
[1, 2, 3, 4, 5, 7, 8, 6]
[1, 2, 3, 4, 5, 6, 8, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]
4


In [211]:
def miniSwaps(arr) :
    count = 0
    
    def swap(idx1, idx2) :
        tmp = arr[idx1]
        arr[idx1] = arr[idx2]
        arr[idx2] = tmp
    
    for i in range(len(arr)) :
        minArr = min(arr[i:len(arr)])
        minIdx = arr[i:len(arr)].index(minArr)+i
        if(minArr < arr[i]) :
            swap(minIdx,i)
            count += 1
        print(arr)
    return(count)

arr = [9, 2, 5, 3, 4, 7, 8, 6]
print(miniSwaps(arr))


[2, 9, 5, 3, 4, 7, 8, 6]
[2, 3, 5, 9, 4, 7, 8, 6]
[2, 3, 4, 9, 5, 7, 8, 6]
[2, 3, 4, 5, 9, 7, 8, 6]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9]
5


In [222]:
def miniSwaps(arr) :
    count = 0
    
    def swap(idx1, idx2) :
        tmp = arr[idx1]
        arr[idx1] = arr[idx2]
        arr[idx2] = tmp
    res = list(range(1,len(arr)+1))
    for j in range(len(arr)-1) :
        for i in range(len(arr)) :
            if arr[i] != i+1 :
                swap(i,arr[i]-1)
                count += 1
        if res == arr :
            break
        
    return(count)

arr = [2, 3, 4, 1, 5]
print(miniSwaps(arr))

3


In [223]:
arr = [1,2,3,4,5]

res = list(range(1,len(arr)+1))

arr == res

True

In [227]:
def mini(arr) :
    i = 0
    count = 0
    while i< len(arr)-1 :
        if arr[i] != i+1 :
            tmp = arr[i]-1
            arr[i], arr[tmp] = arr[tmp], arr[i]
            count += 1
        else : 
            i+=1
        print(arr)
    return(count)
        
        
arr = [2, 3, 4, 1, 5]
print(mini(arr))

[3, 2, 4, 1, 5]
[4, 2, 3, 1, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
3
