In [16]:
import numpy as np
import time

In [6]:
a = [1,2,3,4,5]
b = []
for i in a :
    b.append(i+15)
b

[16, 17, 18, 19, 20]

In [11]:
a = np.array(a)
# a+15 하면 a 에 기록이 안남아 있다리
# a찍으면 결과값이 없다리
c = a+15 
c

array([16, 17, 18, 19, 20])

In [13]:
a = []
b = []
c = []
for i in range(10) :
    a.append(i+1)
    b.append(i+11)

for i in range(len(a)) :
    c.append(a[i]+b[i])
    
c

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

In [14]:
a = []
b = []
c = []
for i in range(10) :
    a.append(i+1)
    b.append(i+11)
    
for i in a :
    c.append(i + b[a.index(i)])
c

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

In [ ]:
# numpy array : vector 연산을 실시함

In [ ]:
# array 빈값등 정확히 안맞으면 오브젝트 타입으로 변환되서 넘어간다
# 딱 맞으면 int64로 넘어감

In [22]:
size_vector = 100000000

def pythonlist(size) :
    t1 = time.time()
    x = range(size)
    y = range(size)
    t2 = time.time()
    print("python list load time : "+str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)) :
        z.append(x[i]+y[i])
    t4 = time.time()
    print("python list for loop : "+str(t4-t3))
    print("python list total : "+str(t4-t1))
    
def numpyarray1(size) :
    t1 = time.time()
    x = np.arange(size)
    y = np.arange(size)
    t2 = time.time()
    print("numpy array1 load time : "+str(t2-t1))
    # z = []
    
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print("numpy array1 for loop : "+str(t4-t3))
    print("numpy array1 total : "+str(t4-t1))
    
def numpyarray2(size) :
    t1 = time.time()
    x = np.arange(size)
    y = np.arange(size)
    t2 = time.time()
    print("numpy array2 load time : "+str(t2-t1))
    
    z = np.ndarray(size)
    t3 = time.time()
    for i in range(len(x)) :
        z[i] = x[i] + y[i]
    t4 = time.time()
    print("numpy array2 for loop : "+str(t4-t3))
    print("numpy array2 total : "+str(t4-t1))
    
print( "size_vector : " +str(size_vector))
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print("---------------------------")

size_vector : 100000000
python list load time : 0.0
python list for loop : 40.9553427696228
python list total : 40.9553427696228
numpy array1 load time : 0.22901296615600586
numpy array1 for loop : 0.15100884437561035
numpy array1 total : 0.3800218105316162
numpy array2 load time : 0.22901320457458496
numpy array2 for loop : 38.1581826210022
numpy array2 total : 38.388195753097534
---------------------------


In [32]:
def square_list0(N) :
    squares = []
    for n in range(N) :
        squares = squares + [n**2]
    return squares

def square_list1(N) :
    squares = []
    for n in range(N) :
        squares += [n**2]
    return squares

def square_list2(N) :
    squares = []
    for n in range(N) :
        squares.append(n**2)
    return squares

def square_list3(N) :
    return [n**2 for n in range(N)]

def square_array(N) :
    #from numpy import arange
    return np.arange(N)**2

def getTime(func, n) :
    t1 = time.time()
    func(n)
    t2 = time.time()
    print(func,'-Try : ', t2-t1)



In [37]:
n = 100000
getTime(square_list0,n)
getTime(square_list1,n)
getTime(square_list2,n)
getTime(square_list3,n)
getTime(square_array,n)



<function square_list0 at 0x000000000575EF78> -Try :  22.74130082130432
<function square_list1 at 0x000000000575EB88> -Try :  0.054003238677978516
<function square_list2 at 0x0000000005736AF8> -Try :  0.052002906799316406
<function square_list3 at 0x0000000005736D38> -Try :  0.04800271987915039
<function square_array at 0x000000000575E798> -Try :  0.0009999275207519531


In [41]:
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(list1)
print(arr1)

print(list1[0])
print(arr1[0])
print('')
print(list1[1:3])
print(arr1[1:3])

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
1
1

[2, 3]
[2 3]


In [67]:
n = 5
a = []
for i in range(n) :
    a_row = []
    for j in range(n) :
        a_row.append(j+i*10)
    a.append(a_row)
print(a)

np.arange(0,6,1)
np.arange(0,51,10)
print(np.arange(0,51,10)[:,np.newaxis]) #축을 바꿔서

b = np.arange(0,51,10)[:,np.newaxis] + np.arange(0,6,1)



[[0, 1, 2, 3, 4], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24], [30, 31, 32, 33, 34], [40, 41, 42, 43, 44]]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]


In [70]:

red = b[:,2]
orange = b[0,3:5]
green = b[2::2,::2]
bluegreen = b[4:,4:]
print(red)
print(orange)
print(green)
print(bluegreen)


[ 2 12 22 32 42 52]
[3 4]
[[20 22 24]
 [40 42 44]]
[[44 45]
 [54 55]]


In [74]:
#boolean indexing : 조건부를 줘서 True인 애들만 가져오는 것

arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [93]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randint(low=30,high=100,size=(7,4))

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[72 33 87 73]
 [93 51 40 35]
 [44 85 81 81]
 [99 99 62 98]
 [74 89 31 62]
 [32 73 78 67]
 [77 37 59 45]]


In [83]:
print(data[names=='Bob'])
print(data[names=='Bob',2:])
print(data[names=='Bob'][0])

print(data[(names=='Bob') | (names=='Will')])

[[42 32 56 30]
 [38 97 31 90]]
[[56 30]
 [31 90]]
[42 32 56 30]
[[42 32 56 30]
 [99 47 31 79]
 [38 97 31 90]
 [33 93 77 90]]


In [94]:
# 성적 기준으로 70기준 pass/fail

data[data<=70] =0
data[data>70] = 1

data

array([[1, 0, 1, 1],
       [1, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 0]])

In [95]:
np.where(data>0)

(array([0, 0, 0, 1, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6], dtype=int64),
 array([0, 2, 3, 0, 1, 2, 3, 0, 1, 3, 0, 1, 1, 2, 0], dtype=int64))

In [96]:
print(names[np.unique(np.where(data>0)[0])])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
